name = "pinkSlime"
output_path = "Atlas"
output_type = "Json"
template_path = ["template.xml"]
folders = [
    "images"
]

[image_options]
output_extension = "Png"
max_size = 4096
show_extension = false

[features]
nine_patch = false
