name = "atlas"
output_path = "output/Vigilante Thief"
output_type = "Json"
template_path = ["template.xml"]
folders = [
                       "output/Vigilante Thief/images"
]

[image_options]
output_extension = "Png"
max_size = 4096
show_extension = false

[features]
nine_patch = false